### PR TITLE
AWS shared credentials file

### PR DESCRIPTION
**Pull request by mukrishn**
## Type of change

- [ ] Refactor
- [ ] New feature
- [ ] Bug fix
- [x] Optimization
- [ ] Documentation Update

## Description

AWS shared credential file path to use a different aws authentication file

## Related Tickets & Documents

- Related Issue #
- Closes #

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.

## Testing
- Please describe the System Under Test.
- Please provide detailed steps to perform tests related to this code change.
- How were the fix/results from this change verified? Please provide relevant screenshots or results.

### CODE REVIEW

**Comment by mukrishn** [comment]
@mohit-sheth ptal

**Review by venkataanil — APPROVED** [review]
LGTM

**Comment by dcbw** [comment]
@mukrishn don't we also need to export AWS_SHARED_CREDENTIALS_FILE for any Ansible task/step that calls `aws` itself too? eg all the stuff in `OCP-4.X/roles/post-config-on-aws/tasks/main.yml` too

**Comment by mukrishn** [comment]
> @mukrishn don't we also need to export AWS_SHARED_CREDENTIALS_FILE for any Ansible task/step that calls `aws` itself too? eg all the stuff in `OCP-4.X/roles/post-config-on-aws/tasks/main.yml` too

right I think they are failed but ignored, let me set the env value there as well.
```
[2023-08-22, 00:11:41 UTC] {subprocess.py:93} INFO - TASK [post-config-on-aws : Get VpcId] ******************************************
[2023-08-22, 00:11:41 UTC] {subprocess.py:93} INFO - task path: /home/airflow/workspace/scale-ci-deploy/OCP-4.X/roles/post-config-on-aws/tasks/main.yml:34
[2023-08-22, 00:11:41 UTC] {subprocess.py:93} INFO - Tuesday 22 August 2023  00:11:41 +0000 (0:00:00.039)       0:37:25.827 ********
[2023-08-22, 00:11:44 UTC] {subprocess.py:93} INFO - changed: [ec2-34-220-44-1.us-west-2.compute.amazonaws.com] => {"changed": true, "cmd": "aws ec2 describe-instances --query 'Reservations[*].Instances[*].[InstanceId,Tags[?Key==`Name`].Value|[0],State.Name,PrivateIpAddress,PublicIpAddress, PrivateDnsName, VpcId]' --output text | column -t | grep mukrishn-hcp-workload-tp7qs | awk '{print $7}' | grep -v '^$' | sort -u", "delta": "0:00:00.650309", "end": "2023-08-22 00:11:44.403124", "msg": "", "rc": 0, "start": "2023-08-22 00:11:43.752815", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
[2023-08-22, 00:11:44 UTC] {subprocess.py:93} INFO - 
[2023-08-22, 00:11:44 UTC] {subprocess.py:93} INFO - TASK [post-config-on-aws : Get security groups] ********************************
[2023-08-22, 00:11:44 UTC] {subprocess.py:93} INFO - task path: /home/airflow/workspace/scale-ci-deploy/OCP-4.X/roles/post-config-on-aws/tasks/main.yml:38
[2023-08-22, 00:11:44 UTC] {subprocess.py:93} INFO - Tuesday 22 August 2023  00:11:44 +0000 (0:00:02.590)       0:37:28.418 ********
[2023-08-22, 00:11:47 UTC] {subprocess.py:93} INFO - changed: [ec2-34-220-44-1.us-west-2.compute.amazonaws.com] => {"changed": true, "cmd": "aws ec2 describe-security-groups --filters \"Name=vpc-id,Values=\" --output json | jq .SecurityGroups[].GroupId", "delta": "0:00:00.738005", "end": "2023-08-22 00:11:47.075182", "msg": "", "rc": 0, "start": "2023-08-22 00:11:46.337177", "stderr": "\nAn error occurred (InvalidParameterValue) when calling the DescribeSecurityGroups operation: vpc-id", "stderr_lines": ["", "An error occurred (InvalidParameterValue) when calling the DescribeSecurityGroups operation: vpc-id"], "stdout": "", "stdout_lines": []}
```

**Comment by mukrishn** [comment]
@dcbw did it work ?

**Comment by dcbw** [comment]
@mukrishn yes, I've been using it for a week or so and it's been great.

**Review by afcollins — APPROVED** [review]
LGTM

**Pull request merged**
