### PR TITLE
Allow post-install to change the OVNK Image for dev

### PR DESCRIPTION
**Pull request by jtaleric**

### CODE REVIEW

**Review by mohit-sheth — APPROVED** [review]
we can just have one var, other than that LGTM

**Comment by jtaleric** [comment]
> we can just have one var, other than that LGTM

ack, I prefer not to have string parsing but 🤷🏽

**Review by whitleykeith — APPROVED** [review]
lgtm

**Review by rsevilla87 — APPROVED** [review]
LGTM!

**Pull request merged**
