### PR TITLE
Removing Dev ES references

### PR DESCRIPTION
**Pull request by vishnuchalla**
## Type of change

- [x] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] Optimization
- [ ] Documentation Update

## Description
Removing Dev ES from the source code references.

## Related Tickets & Documents
- Closes # https://issues.redhat.com/browse/PERFSCALE-3430

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.

### CODE REVIEW

**Comment by vishnuchalla** [comment]
cc: @rsevilla87 @jtaleric @mukrishn

**Comment by rsevilla87** [comment]
cc @mohit-sheth , not sure if this change will affect the playbook, can you verify it?

**Comment by rsevilla87** [comment]
cc: @venkataanil

**Review by mohit-sheth — APPROVED** [review]
lgtm

**Comment by vishnuchalla** [comment]
Confirming that this change is harmless. We have airflow already using our [prod ES](https://vault.apps.sailplane.perf.lab.eng.rdu2.redhat.com/ui/vault/secrets/airflow/show/variables/elasticsearch) instance [from the vault](https://github.com/search?q=repo%3Acloud-bulldozer%2Fairflow-kubernetes+var_loader.get_secret%28%27elasticsearch%27%29&type=code).

**Pull request merged**
