### PR TITLE
Allow deploying custom CNO image with openshift_cno_image

### PR DESCRIPTION
**Pull request by dcbw**
Like we do for OVN-Kube images.

### CODE REVIEW

**Review by venkataanil — COMMENTED** [review]
Not sure if this works (as "environment:" param doesn't work for block). I am already using https://github.com/cloud-bulldozer/scale-ci-deploy/pull/207 to override CNO for deploying OVN-IC.

**Comment by dcbw** [comment]
@venkataanil just below this though, the `relay` code uses the same pattern though:

```
  - name: Wait for OVNK new master images to roll out
    command: oc rollout status -n {{ ovn_namespace }} ds/ovnkube-master
  
  - name: OVN SBDB block
    block:
    - name: Deploy ovnkube-sbdb-relay
      script: sbdb-relay.sh deploy
    
    - name: Wait for OVNK sbdb-relay images to roll out
      command: oc rollout status -n {{ ovn_namespace }} deployment.apps/ovnkube-sbdb-relay
    
    - name: Verify ovnkube-sbdb-relay connectivity
      script: sbdb-relay.sh verify
    when: openshift_toggle_ovn_relay|bool
```

**Comment by venkataanil** [comment]
I was only working on patching ovn and sno images. So I didn't touch openshift_toggle_ovn_relay part. I will report an issue in scale-ci-deploy to fix the tasks in "openshift_toggle_ovn_relay" block.

**Review by rsevilla87 — APPROVED** [review]
lgtm

**Comment by venkataanil** [comment]
lgtm, I will close my PR.

**Review by venkataanil — APPROVED** [review]

**Review by jtaleric — APPROVED** [review]
lgtm

**Pull request merged**
